kind: pipeline
type: docker
name: jellyfin-deploy

services:
  - name: docker
    image: docker:dind
    privileged: true
    volumes:
      - name: docker-sock
        path: /var/run

steps:
  - name: deploy
    image: docker/compose:latest
    environment:
      DOCKER_HOST: tcp://docker:2376
      DOCKER_TLS_CERTDIR: ""
    commands:
      - docker compose down || true
      - docker compose pull
      - docker compose up -d
    when:
      branch:
        - main
      event:
        - push

volumes:
  - name: docker-sock
    temp: {}
